branch-defaults:
  master:
    environment: a-env
    group_suffix: null
global:
  application_name: maps_test_v1
  branch: null
  default_ec2_keyname: maps
  default_platform: Ruby 2.3 (Puma)
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: git
